site_name: hello-java
repo_name: GepengCn/hello-java
repo_url: https://github.com/GepengCn/hello-java.git
edit_uri: https://github.com/GepengCn/hello-java/tree/main/docs/
copyright: Copyright &copy; 2023 gepeng
extra:
    generator: false
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/GepengCn/hello-java
          name: gepeng
theme:
    features:
        - content.action.edit
        - content.code.annotate
        - content.code.copy
        - content.tabs.link
        - content.tooltips
        - navigation.tabs
        - navigation.sections
        - navigation.top
        - navigation.footer
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
    icon:
        repo: fontawesome/brands/git
        logo: material/library
    name: material
    language: zh
    font:
#        text: Noto Serif SC
#        code: Fira Mono
    palette:
        - scheme: default
          primary: light green
          accent: light green
          toggle:
                icon: material/brightness-7
                name: Switch to dark mode
        - scheme: slate
          primary: green
          accent: green
          toggle:
                icon: material/brightness-4
                name: Switch to light mode
extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - attr_list
    - tables
    - md_in_html
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

nav:
    - 首页: index.md
    - 算法:
        - 数据结构:
            - 数组: array/array.md
            - 链表: linkedlist/linkedlist.md
            - 栈: stack/stack.md
            - 队列: queue/queue.md
            - 树:
                - 二叉树: tree/binary_tree.md
                - 二叉查找树: tree/binary_search_tree.md
                - AVL树: tree/avl_tree.md
                - 2-3查找树: tree/2_3_tree.md
                - 红黑树: tree/red_black_tree.md
            - 堆: heap/heap.md
            - 图: graph/graph.md
        - 排序:
            - 排序: sort/sort.md
            - 选择排序: sort/selection_sort.md
            - 冒泡排序: sort/bubble_sort.md
            - 插入排序: sort/insertion_sort.md
            - 希尔排序: sort/shell_sort.md
            - 堆排序: sort/heap_sort.md
            - 归并排序: sort/merge_sort.md
            - 快速排序: sort/quick_sort.md
            - 计数排序: sort/counting_sort.md
        - 算法技巧:
            - 贪婪算法: tips/greedy.md
            - 分治算法: tips/divide_conquer.md
            - 动态规划: tips/dynamic.md
            - 随机化算法: tips/random.md
            - 回溯算法: tips/backtracking.md